#!/bin/bash

TARGET="`janosh -r get /target`"
TARGET_SIZE="`janosh size /$TARGET/.`"
declare -A TARGET_ARRAY="`janosh get /$TARGET/.`"

seq 0 $[ $TARGET_SIZE - 1 ] | while read i; do
  janosh -r get "/$TARGET/#$i"
done

